name: C/C++ CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt update && sudo apt install libsdl2-dev
    - run: g++ main.cpp -lSDL2 -o zmeyka
    - run: ./zmeyka || true
    - uses: actions/upload-artifact@v4
      with:
        name: zmeyka
        path: zmeyka
